apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- petstore-openapi-v1-pets-apidoc.yaml 
- petstore-openapi-v1-users-apidoc.yaml
- petstore-openapi-v2-full-apidoc.yaml
- petstore-apiproduct.yaml    
#- petstore-portal.yaml
- petstore-portal-wstatic.yaml
#- dev-environment.yaml
- dev-environment-wplan.yaml
- external-petstore-portal.yaml
- external-environment-wplan.yaml

#patchesStrategicMerge:
#- patch/domain-patch.yaml
#- patch/tls-patch.yaml