apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: ecommerce-portal
  namespace: default
spec:
  displayName: Internal E-commerce Portal
  description: Gloo Portal for the Petstore API using internal gateway!
  banner:
    fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  favicon:
    fetchUrl: https://i.imgur.com/QQwlQG3.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/hjgPMNP.png
  customStyling: {}
  staticPages:
  - content:
      configMap:
        key: faq
        name: default-petstore-portal-faq
        namespace: default
    description: Frequently Asked Questions
    displayOnHomepage: true
    name: faq
    navigationLinkName: FAQ
    path: /faq

  domains:
  - portal.example.com

  publishedEnvironments:
  - name: internal-dev
    namespace: default

  allApisPublicViewable: false