apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../app/petstore/swaggerapi/
- ../../../app/petstore-portal
- ../../../config/petstore-portal/

patchesStrategicMerge:
- patch/domain-patch.yaml
- patch/tls-patch.yaml
- patch/portal-patch.yaml