apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: ecommerce-portal
  namespace: default
spec:
  domains:
  - portal.internal.corp
---
apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: external-ecommerce-portal
  namespace: default
spec:
  domains:
  - portal.external.example.com
---
apiVersion: portal.gloo.solo.io/v1beta1
kind: Environment
metadata:
  name: internal-dev
  namespace: default
spec:
  domains:
  - api.internal.corp # the domain name where the API will be exposed
---
apiVersion: portal.gloo.solo.io/v1beta1
kind: Environment
metadata:
  name: external-dev
  namespace: default
spec:
  domains:
    - api.external.example.com # the domain name where the API will be exposed