apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: external-ecommerce-portal
  namespace: default
spec:
  tls:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
---
apiVersion: portal.gloo.solo.io/v1beta1
kind: Environment
metadata:
  name: external-dev
  namespace: default
spec:
  gatewayConfig:
    tls:
      config:
        secretRef:
          name: upstream-tls
          namespace: gloo-system
        sniDomains:
        - '*.external.example.com'
      enabled: true